name: second pipeline

on:
  push: 
    branches: ["develop"]
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: 1st job
        run: echo "first job"


  second-job:
    needs: first-job
    runs-on: ubuntu-22.04
    steps:
      - name: 2nd job
        run: echo "second job"

  third-job:
    needs: first-job
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 3rd job
        run: echo "third job"
